### ISSUE TITLE
Software Development Needs Meta-issue

### ISSUE THREAD

**Issue by ericelliott** [jshomes/jshomes.org#4]
This issue is here to compile various opportunities to contribute to the open source software that JSHomes intends to use. If you don't see a link for one of the items, feel free to suggest on open-source solution that may work, or volunteer to create a solution in the issue comments here.

* [ ] Something like an open-source version of CodePen that allows students to modify embedded code examples for interactive learning
* [ ] [Isomorphic Express Boilerplate](https://github.com/ericelliott/isomorphic-express-boilerplate/issues) (Node app foundations for APIs, etc...)
* [ ] [Production module boilerplate](https://github.com/ericelliott/prod-module-boilerplate) (Node package foundations)
* [ ] Course content editor (see [Woofmark markdown editor](https://github.com/bevacqua/woofmark) for a possible solution).
* [ ] WordPress organization accounts (see [tweet](https://twitter.com/_ericelliott/status/610637401627627520))

## Working Solutions

* [x] [WordPress](https://wordpress.org/) for content management (we'd love to replace this with a Node solution, but WordPress is still lightyears ahead of node CMS solutions right now)
* [x] [Markdown WordPress Plugin](https://wordpress.org/plugins/wp-markdown/)

**Comment by SOSANA** [comment]
Have you checked out keystone cms? https://github.com/keystonejs/keystone

**Comment by ericelliott** [comment]
@SOSANA I don't think that's going to work, but if you don't want to mess with the WordPress stuff, you could [start here](https://github.com/jshomes/nodehomes/issues/2).

**Comment by chrisrhoton** [comment]
For WP authentication via GitHub, perhaps the WP-OAuth plugin? https://github.com/perrybutler/WP-OAuth

**Comment by ericelliott** [comment]
Thanks @chrisrhoton!

**Comment by chrisrhoton** [comment]
Free Code Camp moved from Gitter to Slack and back to Gitter again. Here's [a write up] (http://blog.freecodecamp.com/2015/06/so-yeah-we-tried-slack-and-we-deeply-regretted-it.html) of their experience. Seems relevant given the similar use case.

**Comment by chrisrhoton** [comment]
[Plunkr] (http://plnkr.co) might work if you're looking for something like CodePen but [open source] (https://github.com/filearts/plunker).

**Comment by ericelliott** [comment]
Great @chrisrhoton! Thanks a lot. :fire:

**Comment by hotrannam** [comment]
@ericelliott where can i make a pull request for nodejs api?

**Comment by ericelliott** [comment]
@hotrannam [Here](https://github.com/jshomes/jshomes-platform-api). Please carefully read the [contributing doc](https://github.com/jshomes/jshomes-platform-api/blob/master/docs/contributing/index.md) and understand the Universal React Boilerplate directory conventions and understand the [versioning](https://github.com/jshomes/jshomes-platform-api/blob/master/docs/contributing/versions/index.md) (semver + human readable release names).

**Comment by halhenke** [comment]
@SOSANA I have mucked around with Keystone a fair bit and I think its really nicely designed and has a good chance of one day being the WP replacement people are looking for. However at present it doesnt have any concept of roles - there are only admins with full access to the admin interface and non-admin who cant do anything. That means if there are any resources that you might want a non-admin to be able to CRUD that you have to create all the back end/views per resource and cant hook into the built in Admin interface for this sort of thing. 

Alternatively it probably wouldn't be too much work to fork/patch this functionality in as at least one person has done but obviously not a great long term solution.

**Comment by jonathanp** [comment]
Have you seen that Wordpress is moving away from PHP/MySQL in favour or Node and React?

https://github.com/Automattic/wp-calypso

**Comment by ericelliott** [comment]
@jonathanp Yes. We discussed that with Matt Mullenweg at an Automattic retreat. We're excited that in the long term, there will very likely be a good migration to an all-JavaScript foundation. However, we still currently need to have our own WordPress.org install, and the APIs for WordPress.com and WordPress.org are not yet unified.

It will probably take time for the WordPress.org platform to migrate so that we won't need to have PHP or MySQL installed.

**Comment by hunterlester** [comment]
I have some experience with WordPress and Express. How do I jump in to help?

**Comment by ericelliott** [comment]
Hi Hunter, there are tons of open issues. Pick one up that looks interesting to you and jump in. =)

FYI, the install process may change soon. [See Issue 44](https://github.com/jshomes/JSHomes-Platform/issues/44).

**Comment by sparklebunny** [comment]
I would also like to help. I will dig around and see where I can contribute.

**Comment by halhenke** [comment]
Its certainly an interesting development - thought it was an April Fool's Day thing at first or something.

**Comment by Vheissu** [comment]
I would to love help out with the Wordpress integration stuff. Now that Wordpress is becoming an API powered CMS, we have easier and more options for Javascript integration and data layer logic. How can I help?

**Comment by Cryptolemming** [comment]
Hi I'd like to help but not sure where the JS/React etc fits into the WP project which is all I see atm.  Any  recommendations where to start on [this list](https://github.com/jshomes/JSHomes-Platform/issues/32)?

**Comment by sjones6** [comment]
@ericelliott : Seems like there hasn't been much work on this in a few years. Is the project still active or potentially active?

**Comment by ericelliott** [comment]
Platform development has moved to a private repo, and quite a lot of progress has been made. We have learned a lot since we started the project, and helped establish refugee training programs (~90,000 refugees enter the United States with few resources each year -- one of the leading sources of America's addressable homeless population).

Our work has also inspired other training initiatives on 3 other continents (South America, Africa, and Europe).

**Comment by sjones6** [comment]
@ericelliott : Thanks for your quick and charitable reply. I subsequently realized that you've mostly answered this on the README.
